package com.auctionxi.exception;

public enum AllocationErrorCode {
    ROOM_NOT_FOUND,
    MEMBER_NOT_FOUND,
    ROOM_FULL,
    AUCTION_ALREADY_STARTED,
    FRANCHISE_INVALID,
    FRANCHISE_ALREADY_TAKEN,
    QUOTA_EXCEEDED,
    NOT_FRANCHISE_OWNER,
    REBALANCE_REQUIRED,
    INVALID_REBALANCE_SELECTION,
    NOT_ROOM_HOST,
    UNOWNED_FRANCHISES_REMAIN,
    QUOTA_INCOMPLETE,
    ROOM_NOT_MUTABLE,
    INVALID_REQUEST,
    MATCH_NOT_FOUND
}
